#!/bin/bash
defaults write .GlobalPreferences com.apple.mouse.scaling -1
defaults write .GlobalPreferences com.apple.trackpad.scaling -1

#Keyboard repeat
defaults write NSGlobalDomain KeyRepeat -int 0
